let cache={token:'',expires:0};
export const text=v=>String(v??'').trim();
export const arr=v=>Array.isArray(v)?v:[];
export const num=(v,d=0)=>Number.isFinite(Number(v))?Number(v):Number(d||0);
export const pad=(v,n=2)=>String(Math.max(0,num(v))).padStart(n,'0');
export const slug=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'_').replace(/^_+|_+$/g,'').slice(0,160)||'sin_nombre';
export const norm=v=>text(v).normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,' ').replace(/\s+/g,' ').trim();
export const now=()=>new Date().toISOString();
export function fail(msg,status=400){const e=new Error(msg);e.status=status;throw e;}
export function reply(data,status=200){return new Response(JSON.stringify(data),{status,headers:{'content-type':'application/json; charset=utf-8','cache-control':'no-store'}})}
function bytes64(s){const bin=atob(s),a=new Uint8Array(bin.length);for(let i=0;i<bin.length;i++)a[i]=bin.charCodeAt(i);return a}
function pemBytes(pem){return bytes64(pem.replace(/-----BEGIN PRIVATE KEY-----/g,'').replace(/-----END PRIVATE KEY-----/g,'').replace(/\s+/g,'')).buffer}
function b64u(s){return btoa(unescape(encodeURIComponent(s))).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
function b64ub(a){let s='';for(let i=0;i<a.length;i++)s+=String.fromCharCode(a[i]);return btoa(s).replace(/=/g,'').replace(/\+/g,'-').replace(/\//g,'_')}
async function token(env){if(text(env.CURRICULO_BEARER_TOKEN))return text(env.CURRICULO_BEARER_TOKEN);if(cache.token&&cache.expires>Date.now()+60000)return cache.token;const email=text(env.CURRICULO_SERVICE_ACCOUNT_EMAIL),pem=text(env.CURRICULO_PRIVATE_KEY).replace(/\\n/g,'\n');if(!email||!pem)fail('Faltan CURRICULO_SERVICE_ACCOUNT_EMAIL y CURRICULO_PRIVATE_KEY en Cloudflare.',503);const t=Math.floor(Date.now()/1000),h=b64u(JSON.stringify({alg:'RS256',typ:'JWT'})),p=b64u(JSON.stringify({iss:email,scope:'https://www.googleapis.com/auth/datastore https://www.googleapis.com/auth/devstorage.read_write',aud:'https://oauth2.googleapis.com/token',iat:t,exp:t+3600}));const key=await crypto.subtle.importKey('pkcs8',pemBytes(pem),{name:'RSASSA-PKCS1-v1_5',hash:'SHA-256'},false,['sign']);const sig=await crypto.subtle.sign('RSASSA-PKCS1-v1_5',key,new TextEncoder().encode(h+'.'+p));const jwt=h+'.'+p+'.'+b64ub(new Uint8Array(sig));const r=await fetch('https://oauth2.googleapis.com/token',{method:'POST',headers:{'content-type':'application/x-www-form-urlencoded'},body:new URLSearchParams({grant_type:'urn:ietf:params:oauth:grant-type:jwt-bearer',assertion:jwt})});if(!r.ok)fail('No se pudo autenticar el Worker con Google.',503);const d=await r.json();cache={token:d.access_token,expires:Date.now()+num(d.expires_in,3600)*1000};return cache.token}
const project=env=>text(env.CURRICULO_PROJECT_ID||'curriculo-ddfcd');
const root=env=>'https://firestore.googleapis.com/v1/projects/'+project(env)+'/databases/(default)/documents';
export const docName=(env,c,id)=>'projects/'+project(env)+'/databases/(default)/documents/'+c+'/'+id;
async function req(env,url,opt={}){const r=await fetch(url,{...opt,headers:{authorization:'Bearer '+await token(env),'content-type':'application/json',...(opt.headers||{})}});if(r.status===404)return null;if(!r.ok){const t=await r.text();fail('Firestore: '+r.status+' '+t.slice(0,250),502)}return r.status===204?{}:r.json()}
function dec(v){if('nullValue'in v)return null;if('stringValue'in v)return v.stringValue;if('integerValue'in v)return Number(v.integerValue);if('doubleValue'in v)return Number(v.doubleValue);if('booleanValue'in v)return !!v.booleanValue;if('timestampValue'in v)return v.timestampValue;if('arrayValue'in v)return arr(v.arrayValue.values).map(dec);if('mapValue'in v){const o={};Object.entries(v.mapValue.fields||{}).forEach(([k,x])=>o[k]=dec(x));return o}return null}
function doc(d){const o={id:(d.name||'').split('/').pop()};Object.entries(d.fields||{}).forEach(([k,v])=>o[k]=dec(v));return o}
function enc(v){if(v===null)return {nullValue:null};if(typeof v==='string')return {stringValue:v};if(typeof v==='boolean')return {booleanValue:v};if(typeof v==='number')return Number.isInteger(v)?{integerValue:String(v)}:{doubleValue:v};if(Array.isArray(v))return {arrayValue:{values:v.map(enc)}};if(v&&typeof v==='object')return {mapValue:{fields:fields(v)}};return {stringValue:String(v)}}
function fields(o){const f={};Object.entries(o||{}).forEach(([k,v])=>{if(v!==undefined)f[k]=enc(v)});return f}
export async function getDoc(env,c,id){const d=await req(env,root(env)+'/'+c+'/'+encodeURIComponent(id));return d?doc(d):null}
export async function setDoc(env,c,id,data){const d=await req(env,root(env)+'/'+c+'/'+encodeURIComponent(id),{method:'PATCH',body:JSON.stringify({fields:fields({...data,id})})});return doc(d)}
export async function delDoc(env,c,id){await req(env,root(env)+'/'+c+'/'+encodeURIComponent(id),{method:'DELETE'})}
export async function query(env,c,field,value){if(!field){const d=await req(env,root(env)+'/'+c+'?pageSize=1000');return arr(d&&d.documents).map(doc)}const q={structuredQuery:{from:[{collectionId:c}],where:{fieldFilter:{field:{fieldPath:field},op:'EQUAL',value:enc(value)}},limit:1000}};const d=await req(env,root(env)+':runQuery',{method:'POST',body:JSON.stringify(q)});return arr(d).filter(x=>x.document).map(x=>doc(x.document))}
export const setWrite=(env,c,id,data)=>({update:{name:docName(env,c,id),fields:fields({...data,id})}});
export async function commit(env,writes){await req(env,'https://firestore.googleapis.com/v1/projects/'+project(env)+'/databases/(default)/documents:commit',{method:'POST',body:JSON.stringify({writes})})}
export async function uploadPdf(env,name,b64){const bytes=bytes64(b64),bucket=text(env.CURRICULO_STORAGE_BUCKET||'curriculo-ddfcd.firebasestorage.app'),u='https://storage.googleapis.com/upload/storage/v1/b/'+encodeURIComponent(bucket)+'/o?uploadType=media&name='+encodeURIComponent(name);const r=await fetch(u,{method:'POST',headers:{authorization:'Bearer '+await token(env),'content-type':'application/pdf'},body:bytes});if(!r.ok){const t=await r.text();fail('No se pudo guardar el PDF en Firebase Storage: '+r.status+' '+t.slice(0,180),502)}return r.json()}
